spring.application.name=netflix
spring.data.mongodb.uri=mongodb://host.docker.internal:27017/netflix
#spring.data.mongodb.uri=mongodb://localhost:27017/netflix
jwt.secret=mysupersecretkeymysupersecretkey
spring.kafka.consumer.properties.spring.json.trusted.packages=*
files.video = videos/
hsl.folder=hsl-videos/
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
save-movie-in-es-ds-preparing-for-the-search=save-movie-in-es-ds-preparing-for-the-search
spring.kafka.bootstrap-servers=kafka:9092
#spring.kafka.bootstrap-servers=http://localhost:9092

#mongodb://localhost:27017/
#debug=true
#spring.data.mongodb.uri=mongodb://localhost:27017/netflix
#spring.security.user.name=admin
#spring.security.user.password=admin
#wzgZCLREVbJXV5S2d5qPmzrNXjgB5KBD5HwUjeMxPKCdSCfCmyQ9bj5myOgp+d1q1WNN1r4kGOKI2LkUPkufoaWtVGTblbuK0V5O49NZI4C0G5FP4Z/A9xm80h0EvWRIaa9lj7f4J3EVQkn44Jbd+nPwxAKXe3ajRHpu7TkVygQ=
## Producer configuration
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
## Consumer configuration
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.group-id=my-consumer-group
#spring.kafka.consumer.auto-offset-reset=earliest