spring.application.name=netflix
spring.data.mongodb.uri=mongodb://localhost:27017/netflix
#
#spring.security.user.name=admin
#spring.security.user.password=admin

#mongodb://localhost:27017/
jwt.secret=mysupersecretkeymysupersecretkey
#wzgZCLREVbJXV5S2d5qPmzrNXjgB5KBD5HwUjeMxPKCdSCfCmyQ9bj5myOgp+d1q1WNN1r4kGOKI2LkUPkufoaWtVGTblbuK0V5O49NZI4C0G5FP4Z/A9xm80h0EvWRIaa9lj7f4J3EVQkn44Jbd+nPwxAKXe3ajRHpu7TkVygQ=

#debug=true

files.video = videos/
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB